version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: todogo
    restart: always
    ports:
      - 8180:8180